services:
    RIPS\ConnectorBundle\Services\APIService:
        public: true
        arguments:
            - '%rips_connector.email%'
            - '%rips_connector.password%'
            -
              base_uri: '%rips_connector.base_uri%'
              timeout: '%rips_connector.timeout%'
              connect_timeout: '%rips_connector.connect_timeout%'
              oauth2: '%rips_connector.oauth2%'

    RIPS\ConnectorBundle\Services\:
        public: true
        exclude: '../../Services/APIService.php'
        arguments:
            - '@rips_connector.api'