services:
    rips_connector.api:
        class: RIPS\ConnectorBundle\Services\APIService
        arguments:
            - '%rips_connector.username%'
            - '%rips_connector.password%'
            -
              base_uri: '%rips_connector.base_uri%'
              timeout: '%rips_connector.timeout%'
              connect_timeout: '%rips_connector.connect_timeout%'

    rips_connector.users:
        class: RIPS\ConnectorBundle\Services\UserService
        arguments:
            - '@rips_connector.api'

    rips_connector.orgs:
        class: RIPS\ConnectorBundle\Services\OrgService
        arguments:
            - '@rips_connector.api'

    rips_connector.quota:
        class: RIPS\ConnectorBundle\Services\QuotaService
        arguments:
            - '@rips_connector.api'

    rips_connector.application:
        class: RIPS\ConnectorBundle\Services\ApplicationService
        arguments:
            - '@rips_connector.api'
